# Generated by Django 5.2.8 on 2025-11-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='health_benefits',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
